<?php
/**
 * @file
 * File to create a modal popup and show an entity inside it.
 */


/**
 * Implements hook_menu().
 */
function modal_entity_menu() {

  // Entity modal.
  $items['modal/%/%ctools_js/%'] = array(
    'page callback' => 'entity_modal_popup_form',
    'page arguments' => array(1, 2, 3),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  // Custom modal.
  $items['custom/modal/%ctools_js/%'] = array(
    'page callback' => 'custom_modal_popup_form',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}


/**
 * Implements hook_init().
 */
function modal_entity_init() {

  // Use Ctools API to initialize a modal popup.
  ctools_include('ajax');
  ctools_include('modal');
  ctools_modal_add_js();
  ctools_add_js('ctools-ajax-form', 'modal_entity');
  ctools_add_css('ctools-ajax-form', 'modal_entity');

  $modal_entity_style = array(
    'ctools-modal-entity-style' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 640,
        'height' => 400,
        'addWidth' => 20,
        'addHeight' => 15,
      ),
      'modalOptions' => array(
        'opacity' => 0.7,
        'background-color' => '#000',
        'overflow' => 'hidden',
      ),
      'animation' => 'slow',
      'modalTheme' => 'CToolsEntityModal',
      'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'ctools_ajax_sample'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
    ),
  );
  drupal_add_js($modal_entity_style, 'setting');
}


/**
 * Implements hook_preprocess_entity().
 */
function modal_entity_preprocess_node(&$vars) {
  if ($vars['node']->type == 'movie' && $vars['view_mode'] == 'entity_modal_view') {
    $vars['theme_hook_suggestions'][] = 'node__movie__entity_modal_view';
  }
}


/**
 * Implements hook_entity_info_alter().
 */
function modal_entity_entity_info_alter(&$entity_info) {

  // Get all entity types.
  $entities = array_keys($entity_info);

  // Add our view mode for each entity.
  foreach($entities as $entity) {
    $entity_info[$entity]['view modes']['entity_modal_view'] = array(
      'label' => t('Entity Modal View'),
      'custom settings' => TRUE,
    );
  }
}


/**
 * Implements menu callback to show a modal popup.
 */
function entity_modal_popup_form($entity_type, $ajax = NULL, $entity_id, $view_mode = 'entity_modal_view') {
  if ($ajax) {

    // Load ctools inc files.
    ctools_include('modal');
    ctools_include('ajax');

    $form_state = array(
      'title' => 'Entity Modal form',
      'ajax' => TRUE,
      'entity_type' => $entity_type,
      'entity_id' => $entity_id,
      'view_mode' => $view_mode,
      'modal_entity_ajax_run' => TRUE,
    );
    $output = ctools_modal_form_wrapper('entity_modal_form', $form_state);

    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }
    print ajax_render($output);
  }
  else {
    return drupal_get_form('entity_modal_form', $entity_type, $entity_id, $view_mode);
  }
}


/**
 * Entity form that is shown inside modal popup.
 */
function entity_modal_form($form, &$form_state, $entity_type, $entity_id, $view_mode) {
  if (isset($form_state['modal_entity_ajax_run'])) {
    $entity_type = $form_state['entity_type'];
    $entity_id = $form_state['entity_id'];
    $view_mode = $form_state['view_mode'];
  }

  // Load entity.
  $entity = entity_load($entity_type, array($entity_id));

  // Render entity.
  $form['check'] = array(
    '#markup' => drupal_render(entity_view($entity_type, $entity, $view_mode)),
  );
  return $form;
}


/**
 * Implements menu callback to show a modal popup.
 */
function custom_modal_popup_form($ajax = NULL, $formid) {
  if ($ajax) {

    // Load ctools inc files.
    ctools_include('modal');
    ctools_include('ajax');

    $form_state = array(
      'title' => 'Custom Modal form',
      'ajax' => TRUE
    );
    $output = ctools_modal_form_wrapper($formid, $form_state);

    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }
    print ajax_render($output);
  }
  else {
    return drupal_get_form($formid);
  }
}
